### ISSUE TITLE
rdf:langstring or rdf:plainliteral support

### ISSUE THREAD

**Issue by mahdanoura** [w3c/wot-thing-description-toolchain-tmp#19]
Json-LD support rdf:langString, and the TD utilizes this in the attributes title, titles, description and descriptions. However, providing this type in LinkML using the following:
```
types:
  MultiLanguage:
    name: MultiLanguage
    description: Description with a language tag.
    from_schema: https://raw.githubusercontent.com/w3c/wot-thing-description/main
    exact_mappings:
    - rdf:langString
    base: rdf:PlainLiteral
    uri: rdf:PlainLiteral
```
results in pure string.
